alias lixo='dd if=/dev/zero of=file.txt count=1024 bs=1048576'
alias rm='rm -Iv'
alias mv='mv -iv'
alias cp='cp -iv'
alias ls='ls --color=auto --group-directories-first'
alias els='els --els-icons=fontawesome'
alias ufw='sudo ufw'
alias copiar='xclip -sel clip <'
alias e='exit'
alias s='sudo su'
alias pacman='sudo pacman'
alias mkdir='mkdir -pv'
alias neofetch='neofetch --config ~/.neofetch.conf'
alias baixarmp3='youtube-dl --extract-audio --audio-format mp3'
alias baixarlista='youtube-dl --username sistematico --extract-audio --audio-format mp3 -o "%(title)s.%(ext)s"'
alias fullsync='rsync -aAXvz --exclude={"/dev/*","/proc/*","/sys/*","/tmp/*","/run/*","/mnt/*","/media/*","/lost+found","/var/tmp/","/lost+found",".vzfifo",".cpt_hardlink*",".autorelabel"}'
alias pacman-clean='sudo pacman -Qdtq | pacman -Rs -'
alias vim="vim -c 'startinsert'"
alias showip='curl icanhazip.com'
alias lostfiles='sudo lostfiles strict | egrep -vi "/usr/share/themes|-disabled"'
alias yay='yay --noconfirm'
