#! /bin/sh

sxhkd &

#bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor -d I II III IV V VI

bspc config border_width			2
bspc config window_gap				9

bspc config split_ratio				0.50
bspc config focus_follows_pointer	true

bspc config borderless_monocle   	false
bspc config gapless_monocle      	true
bspc config paddingless_monocle	 	false

bspc config normal_border_color		"#4c566a"
bspc config focused_border_color	"#5e81ac"
bspc config presel_feedback_color 	"#5e81ac"

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
bspc rule -a Firefox desktop='^1'
bspc rule -a Termite desktop='^2' focus=on
bspc rule -a Pluma desktop='^3' focus=on
bspc rule -a Sublime_text desktop='^3' focus=on
bspc rule -a Thunar desktop='^4' focus=on
bspc rule -a TelegramDesktop desktop='^5' focus=on
bspc rule -a Mpv state=floating
bspc rule -a Agave state=floating

~/.config/polybar/bspwm.sh &
hsetroot -solid '#2e3440' &
dunst -config ~/.config/dunst/nord &
compton -b &
clipit &
# sudo headsetcontrol 64
xset r rate 300 75 &
thunar --daemon &
#dropbox
#firefox-developer
~/.local/bin/xautolock &
