#!/bin/bash

icone="/usr/share/icons/Faience/actions/64/gnome-lockscreen.png"
PID=$(ps ax | grep -v grep | grep xautolock)


if [[ $BLOCK_BUTTON -eq 1 ]]; then
	if [[ ! -z "$PID" ]]; then
		pkill -9 xautolock
		pkill -9 i3lock
	else
		xautolock -time 5 -locker "i3lock-fancy -f Iosevka-Thin -t 'Arch Linux' -p -- scrot -z" -detect -notify 30 -notifier "notify-send -i $icone --urgency=critical 'TRAVANDO a tela em 30 segundos'"
	fi
fi

if [[ $BLOCK_BUTTON -ge 2 ]]; then
	if [[ -z "$PID" ]]; then
		sleep 1
		exec i3lock-fancy -f Iosevka-Thin -t "Arch Linux" -p -g -- scrot -z
	fi
fi	

if [[ ! -z "$PID" ]]; then
	echo ""
	echo ""
	echo "#3465a4"
else
	echo ""
	echo ""
	echo ""
fi

