#!/bin/bash

. ~/.config/i3/cores.conf

PACKAGE_COUNT=$(checkupdates | wc -l)

# Left click
if [[ "${BLOCK_BUTTON}" -eq 1 ]]; then
    if [[ ${PACKAGE_COUNT} -gt 0 ]]; then
		i3-sensible-terminal -e 'sudo pacman -Syu'
	else
		notify-send "Aviso" "Nenhum pacote para atualizar!"
	fi
# Middle click
elif [[ "${BLOCK_BUTTON}" -eq 2 ]]; then
    pamac-updater
# Right click
elif [[ "${BLOCK_BUTTON}" -eq 3 ]]; then
	pamac-manager
fi

if [[ ${PACKAGE_COUNT} -gt 50 ]]; then
	cor=$cormax
elif [[ ${PACKAGE_COUNT} -gt 20 ]]; then
	cor=$cormed
elif [[ ${PACKAGE_COUNT} -gt 10 ]]; then
	cor=$cormin
else
	cor=""
fi

echo "${PACKAGE_COUNT}" # full-text
echo "${PACKAGE_COUNT}" # short-text
echo "$cor"
