#!/bin/bash
# Script feito por Lucas Saliés Brum, a.k.a. sistematico

url="https://rss.tecmundo.com.br/feed"
abretag1="<item><title>"
fechatag1="</title>"
abretag2="<link>"
fechatag2="</link>"
aleatorio=$(shuf -i 1-10 -n 1)
offset=3
temp="/tmp/rss.txt"

if [[ "$1" = "-o" || $BLOCK_BUTTON -eq 1 ]]; then
	$BROWSER $(cat $temp | tail -n1)
    noticia=$(cat $temp | head -n1 | /usr/local/bin/strcut.py)
    echo $noticia
    echo $noticia
elif [[ "$1" = "-f" || $BLOCK_BUTTON -eq 2 || $BLOCK_BUTTON -eq 3 ]]; then
	# curl --silent "https://rss.tecmundo.com.br/feed" | grep -oP "(?<=<item><title>).*?(?=</title>)" | awk "NR > 1 { print }" | awk "NR==5"
	curl --silent "$url" | grep -oP "(?<=${abretag1}).*?(?=${fechatag1})" | awk "NR > 0 { print }" | awk "NR==${aleatorio}" > $temp
	# curl --silent "https://rss.tecmundo.com.br/feed" | grep -oP "(?<=<link>).*?(?=</link>)" | awk "NR > 1 { print }" | awk "NR==5"
	curl --silent "$url" | grep -oP "(?<=${abretag2}).*?(?=${fechatag2})" | awk "NR > 2 { print }" | awk "NR==${aleatorio}" >> $temp
    noticia=$(cat $temp | head -n1 | /usr/local/bin/strcut.py)
    echo $noticia
    echo $noticia
else
	if [ -f $temp ]; then
		noticia=$(cat $temp | head -n1 | /usr/local/bin/strcut.py)
	else
	    curl --silent "$url" | grep -oP "(?<=${abretag1}).*?(?=${fechatag1})" | awk "NR > 1 { print }" | awk "NR==${aleatorio}" > $temp
    	curl --silent "$url" | grep -oP "(?<=${abretag2}).*?(?=${fechatag2})" | awk "NR > 2 { print }" | awk "NR==${aleatorio}" >> $temp
		noticia=$(cat $temp | head -n1 | /usr/local/bin/strcut.py)
	fi
	echo $noticia
	echo $noticia
fi
