#!/bin/bash

. ~/.config/i3/cores.conf

med=50
max=75
saida=""

if [ "$BLOCK_INSTANCE" = "cpu" ]; then

	if [[ "${BLOCK_BUTTON}" -eq 1 ]]; then
		exec lxtask
	fi

	cpu=$(awk '/cpu /{print 100*($2+$4)/($2+$4+$5)}' /proc/stat)
	saida=$(echo "scale=1;${cpu}/1" | bc)

elif [ "$BLOCK_INSTANCE" = "mem" ]; then

	if [[ "${BLOCK_BUTTON}" -eq 1 ]]; then
		exec mate-disk-usage-analyzer
	fi

	mem=$(free -m | awk 'NR==2{print $3*100/$2 }' | tr -d ' ')
	saida=$(echo "scale=1;${mem}/1" | bc)

elif [ "$BLOCK_INSTANCE" = "disk" ]; then

	if [[ "${BLOCK_BUTTON}" -eq 1 ]]; then
		exec mate-disk-usage-analyzer
	fi

	saida=$(df -h | awk '$NF=="/"{print $5}' | tr -d ' ' | sed -e 's/[^0-9]/ /g')

fi

if [[ $(echo "scale=0;${saida}/1" | bc | sed -e "s/[^0-9]/ /g") -gt $max ]]; then
	cor=$cormax		
elif [[ $(echo "scale=0;${saida}/1" | bc | sed -e "s/[^0-9]/ /g") -gt $med ]]; then	
	cor=$cormed
else
	cor=""	
fi

echo "${saida}%" # full
echo "${saida}%" # short
echo "$cor"   # cor
