#!/bin/bash

. ~/.config/i3/cores.conf

TRASH_DIRECTORY="${BLOCK_INSTANCE}"
TRASH_TEMP="/tmp/lixo"

if [[ "${TRASH_DIRECTORY}" = "" ]]; then
  TRASH_DIRECTORY=${XDG_DATA_HOME:-"${HOME}/.local/share/Trash"}
fi

# Left click
if [[ "${BLOCK_BUTTON}" -eq 1 ]]; then
  xdg-open "${TRASH_DIRECTORY}/files"
# Middle click
elif [[ "${BLOCK_BUTTON}" -eq 2 ]]; then
	rmlint --gui
# Right click
elif [[ "${BLOCK_BUTTON}" -eq 3 ]]; then
	#rm -r "${TRASH_DIRECTORY}/files"
	#rm -r "${TRASH_DIRECTORY}/info"

	if [ ! -d $TRASH_TEMP ]; then
		mkdir $TRASH_TEMP
	fi

	mv ${TRASH_DIRECTORY}/files ${TRASH_TEMP}/
	mv ${TRASH_DIRECTORY}/info ${TRASH_TEMP}/

	mkdir ${TRASH_DIRECTORY}/files
	mkdir ${TRASH_DIRECTORY}/info
fi

TRASH_COUNT=$(ls -U -1 "${TRASH_DIRECTORY}/files" | wc -l)

if [[ ${TRASH_COUNT} -gt 60 ]]; then
	cor=$cormax
elif [[ ${TRASH_COUNT} -gt 40 ]]; then
	cor=$cormed
elif [[ ${TRASH_COUNT} -gt 20 ]]; then
	cor=$cormin
else
	cor=""
fi

echo "${TRASH_COUNT}"
echo "${TRASH_COUNT}"
echo "$cor"

#if [[ "${TRASH_COUNT}" -ge "${URGENT_VALUE}" ]]; then
#  exit 33
#fi
