#!/bin/bash

apps=(
'i3 Config'
'i3 Blocks'
'LX Appearance'
'Dunst'
'Compton'
'Rofi'
'Rofi Apps'
'Rofi Power'
'Rofi Configs'
'.Xresources'
'.xinitrc'
'.xprofile'
'.Xdefaults'
)

res=$( printf "%s\n" "${apps[@]}" | rofi -dmenu -p "Rofi Apps" -bw 0 -lines 13 -separator-style none -location 0 -width 250 -hide-scrollbar -padding 5)

if [ "$res" ]; then
	case $res in
		'i3 Config') i3-msg exec pluma ~/.config/i3/config	;;
		'i3 Blocks') i3-msg exec pluma ~/.config/i3/blocks ;;
		'LX Appearance') i3-msg exec lxappearance ;;
		'Dunst') i3-msg exec pluma ~/.config/dunst/dunstrc ;;
		'Compton') i3-msg exec pluma ~/.config/compton.conf ;;
		'Rofi') i3-msg exec pluma ~/.config/rofi/config ;;
		'Rofi Apps') i3-msg exec pluma ~/.config/rofi/scripts/apps ;;
		'Rofi Power') i3-msg exec pluma ~/.config/rofi/scripts/power ;;
		'Rofi Configs') i3-msg exec pluma ~/.config/rofi/scripts/configs ;;		
		'.Xresources') i3-msg exec pluma ~/.Xresources ;;
		'.xinitrc') i3-msg exec pluma ~/.xinitrc ;;
		'.xprofile') i3-msg exec pluma ~/.xprofile ;;
		'.Xdefaults') i3-msg exec pluma ~/.Xdefaults ;;
	esac
fi
