#!/bin/bash

apps=(
'i3 Config'
'i3 Blocks'
'Dunst'
'Compton'
'Rofi'
'.Xresources'
'.xinitrc'
'.Xdefaults'
'Rofi Apps'
'Rofi Power'
)

res=$( printf "%s\n" "${apps[@]}" | rofi -dmenu -p "Rofi Apps" -bw 0 -lines 11 -separator-style none -location 0 -width 250 -hide-scrollbar -padding 5)

if [ "$res" ]; then
	case $res in
		'i3 Config') i3-msg exec pluma ~/.config/i3/config	;;
		'i3 Blocks') i3-msg exec pluma ~/.config/i3/blocks ;;
		'Dunst') i3-msg exec pluma ~/.config/dunst/dunstrc ;;
		'Compton') i3-msg exec pluma ~/.config/compton.conf ;;
		'Rofi') i3-msg exec pluma ~/.config/rofi/config ;;
		'.Xresources') i3-msg exec pluma ~/.Xresources ;;
		'.xinitrc') i3-msg exec pluma ~/.xinitrc ;;
		'.Xdefaults') i3-msg exec pluma ~/.Xdefaults ;;
		'Rofi Apps') i3-msg exec pluma ~/.config/i3/blocks ;;
		'Rofi Power') i3-msg exec pluma ~/.config/i3/blocks ;;
	esac
fi
