#!/bin/bash

tema="~/.local/share/rofi/themes/sistematico-dark.rasi"

function programado() {
	letras=$(echo "$2" | tr -dc '[a-z][A-Z]')
	numeros=$(echo "$2" | tr -dc '[0-9]')
	#notify-send "Desligamento Programado" "O computador será desligado daqui a ${numeros} ${letras}"

	if [[ $letras == hora* ]]; then
		tmp="hour"
	elif [[ $letras == minuto* ]]; then
		tmp="minute"
	fi
	
	quando=$(date -d "+${numeros} ${tmp}" '+%H:%M')
	notify-send "$1 programado" "a tarefa será executada em ${quando}"

	if [ "$1" == "Desligamento" ]; then
		sudo shutdown -P "$quando"
	elif [ "$1" == "Suspensao" ]; then
		at "$quando" systemctl suspend
	fi
}

res=$(echo "desligar;reiniciar;suspender;programado;travar;sair;cancelar" | rofi -theme "$tema" -sep ";" -dmenu -p "Rofi Power" -bw 0 -lines 7 -separator-style none -location 0 -width 10 -hide-scrollbar -padding 5)

if [ ! -z $res ]; then
	case $res in
		desligar)
			confirma=$(echo -e "Sim\nNão" | rofi -theme "$tema" -dmenu -p "Confirma?" -bw 0 -lines 2 -separator-style none -location 0 -width 7 -hide-scrollbar -padding 5)
			[ $confirma = "Sim" ] && systemctl poweroff
		;;
		reiniciar)
			confirma=$(echo -e "Sim\nNão" | rofi -theme "$tema" -dmenu -p "Confirma?" -bw 0 -lines 2 -separator-style none -location 0 -width 7 -hide-scrollbar -padding 5)
			[ $confirma = "Sim" ] && systemctl reboot
		;;
		suspender)
			suspende=$(echo -e "Sim\nNão" | rofi -theme "$tema" -dmenu -p "Confirma?" -bw 0 -lines 2 -separator-style none -location 0 -width 7 -hide-scrollbar -padding 5)
			[ "$suspende" = "Sim" ] && systemctl suspend
		;;		
		programado)
			tempo=$(echo "5 minutos;10 minutos;15 minutos;30 minutos;45 minutos;1 hora;2 horas;3 horas;4 horas" | rofi -theme "$tema" -sep ";" -dmenu -p "Rofi Power" -bw 0 -lines 9 -separator-style none -location 0 -width 10 -hide-scrollbar -padding 5)
			acao=$(echo "Suspensao;Desligamento" | rofi -theme "$tema" -sep ";" -dmenu -p "Ação" -bw 0 -lines 2 -separator-style none -location 0 -width 7 -hide-scrollbar -padding 5)
			confirma=$(echo -e "Sim\nNão" | rofi -theme "$tema" -dmenu -p "Confirma?" -bw 0 -lines 2 -separator-style none -location 0 -width 7 -hide-scrollbar -padding 5)
			[ $confirma = "Sim" ] && programado "$acao" "$tempo"
		;;
		travar)
			i3-msg -q 'exec i3lock-fancy -f Iosevka-Thin -t "Arch Linux" -p -- scrot -z'
		;;
		sair)
			confirma=$(echo -e "Sim\nNão" | rofi -theme "$tema" -dmenu -p "Confirma?" -bw 0 -lines 2 -separator-style none -location 0 -width 7 -hide-scrollbar -padding 5)
			[ $confirma = "Sim" ] && i3-msg exit
		;;
		*)
		;;
	esac
fi

