#!/bin/bash
# Códigos: 

. ~/.config/i3blocks/cores.conf

nome="screencast"
extensao="mp4"
preset="superfast" # ultrafast,superfast,veryfast,faster,fast,medium,slow,slower,veryslow,placebo
caminho="${HOME}/video"
data=$(date +%Y-%m-%d_%H-%M-%S)
icone="/usr/share/icons/Arc/devices/24@2x/video-display.png"
arquivo="${caminho}/${nome}-${data}.${extensao}"
resolucao=$(xrandr | grep '*' | awk 'NR==1{print $1}')
audio=$(pacmd list-sinks | grep -A 1 'index: 1' | awk 'NR==2{print $2}' | awk '{print substr($0,2,length($0)-2)}')
ativo=$(tmux ls | awk -F':' '{print $1}' | grep $nome | tr -d '[:blank:]')
cor=""
	
if [[ "$ativo" != "$nome" ]]; then
	cor=""
else
	cor="$vermelho"
fi	
		
if [[ $BLOCK_BUTTON -eq 1 ]]; then
	if [[ "$ativo" != "$nome" ]]; then
		tmux new-session -d -s $nome "ffmpeg -thread_queue_size 512 -f x11grab -r 30 -s $resolucao -i :0.0 -f pulse -i default -preset $preset -c:v libx264 -c:a aac -b:a 128k -probesize 50M $arquivo"
	else
		tmux kill-session -t $nome
		killall ffmpeg
		notify-send -i $icone "ScreenCast" "O vídeo <b>$arquivo</b> foi terminado."
	fi
fi

echo "" # full
echo "" # short
echo "$cor"

