#!/bin/bash

LOCAL='EUR|DE|GM011|AACHEN'
METRICA=1 #Should be 0 or 1; 0 for F, 1 for C
URL="http://rss.accuweather.com/rss/liveweather_rss.asp?metric=${METRICA}&locCode=${LOCAL/ /+}"

cond=$(curl -s $URL | grep -iPo '(?<=<title>Currently:)(.*)(?=</title>)' | tr -d '[0-9][:punct:]' | sed 's/.$//' | sed -e 's/^[[:space:]]*//')

case "$cond" in
	*"A thunderstorm in spots"*) 	trad='Trovoadas' ;;
	*"Partly Cloudy"*) 				trad='Nuvens Esparsas' ;;
	*"Mostly Cloudy"*) 				trad='Nuvens Esparsas' ;;
	*"Clear"*) 						trad='Limpo' ;;
	*"Sunny"*) 						trad='Ensolarado' ;;
esac

echo "$trad"
echo "$cond"