#!/bin/bash

. ~/.config/i3blocks/cores.conf

i3blocks_config="${HOME}/.config/i3blocks/config"

function switchi3 {
	atual=$(basename $(readlink -f $i3blocks_config))

	if [ ! -z $atual ]; then
		case $atual in
			config.airblader) 
				ln -sf ${i3blocks_config}.clean ${i3blocks_config}
				cor="$azul"
				i3-msg restart
			;;
			config.clean) 
				ln -sf ${i3blocks_config}.airblader ${i3blocks_config} 
				cor="$vermelho"
				i3-msg -q restart
			;;
			# *) i3-msg -q "exec $res" ;;
		esac
	fi

	echo ""
	echo ""
	echo "$cor"	
}

case $BLOCK_BUTTON in
	1) switchi3 ;;
#	1) notify-send "Data" "$(date '+%d/%m/%Y')" ;;  # left click, pause/unpause
#	2) notify-send "Data" "$(date '+%A')" ;;  # middle click, show info
#	3) notify-send "Data" "$(date '+%A')" ;;  # right click, gmpc
#    4) mpc prev | filter ;;  # scroll up, previous
#    5) mpc next | filter ;;  # scroll down, next
#    *) switchi3 ;;
esac

echo ""
echo ""
echo "$cor"
